<a href="https://colab.research.google.com/github/soyaasha/Sombrano_CS3B_CSST101/blob/main/CSST101_%7C_R_Program.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **My First R Program**

In [ ]:
print ("Hello Universe")

[1] "Hello Universe"

2. Variables & Data Types

In [ ]:
myString <- ("Hello World")
num <- 10
floatingNum <- 9.5
isBool <- TRUE

class(myString)
class(num)
class(floatingNum)
class(isBool)

[1] "character"

[1] "numeric"

[1] "numeric"

[1] "logical"

3. Numerical operators

In [ ]:
x <- 5
y <- 3

add <- x + y
sub <- x - y
mul <- x * y
div <- x / y

print(add)
print(sub)
print(mul)
print(div)


cat("+", add)
cat("-", sub)
cat("*", mul)
cat("/", div)

4. User Input

In [ ]:
name <- readline("Enter your name: ")
age <- readline("Enter your age: ")

print(paste("Name:", name))
print(paste("Age:", age))

5. Decision Making

In [ ]:
grade <- 60

if(grade <75) {
  print ("Failed")
}else{
  print ("Passed")
}

[1] "Failed"

In [ ]:
grade <- readline("Enter grade: ")

if(grade <75) {
  print ("Failed")
}else{
  print("Passed")
}

Enter grade: 80
[1] "Passed"

6. Loop

In [ ]:
for(i in 1:5){
  print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5

7. Functions

In [ ]:
addNumber <- function(a,b){
  return (a+b)
}

addNumber(5, 3)

[1] 8

8. Vectors

In [ ]:
grades <- c(90, 94, 78, 83, 92)

grades

cat("\nMean: ",mean(grades))
cat("\nMax: ",max(grades))
cat("\nMin: ",min(grades))
cat("\nSum: ",sum(grades))
cat("\nLength: ",length(grades))

[1] 90 94 78 83 92

Mean:  87.4
Max:  94
Min:  78
Sum:  437
Length:  5

9.Matrices

In [ ]:
A <- matrix(c(1,2,3,4,5,6),nrow=2)
A

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

10. Lists

In [ ]:
student <- list(
  Name="Mrincess",
  Age=20,
  GPA=1.00
)

student

$Name
[1] "Mrincess"

$Age
[1] 20

$GPA
[1] 1

11. Data Frames

In [ ]:
students <- data.frame(
  Name=c("Mrincess", "Allisha", "Cruz"),
  Age=c(18, 19, 20),
  GPA=c(1.00, 1.25, 1.50)
)

students

write.csv(students,"student.csv")

  Name     Age GPA
1 Mrincess 18  1.00
2 Allisha  19  1.25
3 Cruz     20  1.50

12. Reading CSV Files

In [ ]:
data <- read.csv("...student.csv")

head(data)

summary(data)

  X Name     Age GPA
1 1 Mrincess 18  1.00
2 2 Allisha  19  1.25
3 3 Cruz     20  1.50

       X              Name        Age            GPA
 Min.   :1.0   Length   :3   Min.   :18.0   Min.   :1.000
 1st Qu.:1.5   N.unique :3   1st Qu.:18.5   1st Qu.:1.125
 Median :2.0   N.blank  :0   Median :19.0   Median :1.250
 Mean   :2.0   Min.nchar:4   Mean   :19.0   Mean   :1.250
 3rd Qu.:2.5   Max.nchar:8   3rd Qu.:19.5   3rd Qu.:1.375
 Max.   :3.0                 Max.   :20.0   Max.   :1.500